SELECT USER_ID
     , DATE_FORMAT(ASSAY_DATE, '%Y/%m/%d') AS ASSAY_DATE_FMT
     , ROUND(AVG(DISTINCT HEART_RATE)) AS HEART_RATE
  FROM HEALTH_INFO
 WHERE USER_ID    IS NOT NULL
   AND HEART_RATE IS NOT NULL
   AND ASSAY_DATE IS NOT NULL
 GROUP BY USER_ID
        , DATE_FORMAT(ASSAY_DATE, '%Y/%m/%d')
 ORDER BY DATE_FORMAT(ASSAY_DATE, '%Y/%m/%d')
        , USER_ID